### ISSUE TITLE
axios is send incorrect request content-type "application/json"

### ISSUE THREAD

**Issue by hardywu** [rubykube/mikroapp#12]
peatio v2 currently is supporting the content-type, `application/x-www-form-urlencoded`, only

**Comment by HafeezRai** [comment]
how can we send json i have tried to change to 'application/json'

**Comment by hardywu** [comment]
@HafeezRai  No, you can not. Grape API requires lots of dirty code changes to support "application/json"  type.  Grape maintainers plan not to make it easy in the near future.

**Comment by HafeezRai** [comment]
import axiosInstance from './requestBuilder';


export const logoutUser = () => {
  return axiosInstance.delete('/api/v2/barong/identity/sessions')
    .then(response => response.data)
};

export const loginUser = (email, password, otp_code='', recaptcha_response='') => {
  return axiosInstance.post(
      '/api/v2/barong/identity/sessions',
      { email, password, otp_code, recaptcha_response },
      { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
    )
    .then(response => response.data)
};
This request is going in form encoded form it should be in json format

**Comment by hardywu** [comment]
> import axiosInstance from './requestBuilder';
> 
> export const logoutUser = () => {
> return axiosInstance.delete('/api/v2/barong/identity/sessions')
> .then(response => response.data)
> };
> 
> export const loginUser = (email, password, otp_code='', recaptcha_response='') => {
> return axiosInstance.post(
> '/api/v2/barong/identity/sessions',
> { email, password, otp_code, recaptcha_response },
> { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
> )
> .then(response => response.data)
> };
> This request is going in form encoded form it should be in json format

That's what I just said. The Peatio Server is using Grape API gem, which is enforcing the 'content-type' to be form encoded.

**Comment by hardywu** [comment]
It is not working actually for POST

**Comment by HafeezRai** [comment]
yes for post it is not working how i can resolve this issue?

**Comment by hardywu** [comment]
> yes for post it is not working how i can resolve this issue?

As I said, no, you can not resolve this issue. Unless you make a pull request of dirty codes changes.

**Comment by hardywu** [comment]
Let's leave the issue for future releases getting ride of grape
